In [1]:
import train_test as TT
import numpy as np


DAY_OF_WEEK = {"MONDAY":1,"TUESDAY":2,"WEDNESDAY":3,"THURSDAY":4,"FRIDAY":5,"SATURDAY":6,"SUNDAY":7}
# DISTRICT = {"A1":1,"A15":2,"A7":3,"B2":4,"B3":5,"C11":6,"C6":7,"D14":8,"D4":9,"E13":10,"E18":11,"E5":12}
# data_num = 20000
# alpha = 0.02
# n_epoch = 50
# train accuracy: 0.467625
# test accuracy: 0.474

W = np.mat([[0.70589358, 0.57894807, 0.57555195, 0.64646587, 0.45634837],
 [0.69749017, 0.56445017, 0.38924738, 0.67382041, 0.68272357],
 [0.67179093, 0.5696221, 0.65087029, 0.95102331, 0.32250566]])
b = np.mat([[0.4704748],
 [0.83051006],
 [-0.48455419]])

# X feature: MONTH, DAY_OF_WEEK, HOUR, LATITUDE-36, LONGTITUDE+78
raw_input = np.array([["4","SATURDAY","23","42.30540715","-71.06547135"],
                 ["9","SUNDAY","19","42.30021944","-71.06311002"],
                 ["2","WEDNESDAY","12","42.34044966","-71.08845935"],
                 ["5","THURSDAY","20","42.2330858","-71.12815697"],
                 ["6","SUNDAY","2","42.34455947","-71.14890849"],
                 ["1","WEDNESDAY","8","42.35241815","-71.06525499"],
                 ["3","FRIDAY","3","42.32866284","-71.08563401"],
                 ["10","WEDNESDAY","0","42.32866284","-71.08563401"],
                ["7","FRIDAY","22","42.23649723","-71.12935123"]])
for i in range(0,raw_input.shape[0]):    
    raw_input[i,1] = DAY_OF_WEEK[raw_input[i,1]]
#     raw_input[i,3] = DISTRICT[raw_input[i,3]]
input = np.mat(raw_input.astype(np.float))

<class 'numpy.matrix'>


In [2]:
# z_score with mean, std from big data
input = input.T
mean = [6.581255,3.9459,13.29537,42.322349287354555,-71.0826005364158]
std = [3.275075209056275,1.9669222633342682,6.271098513267034,0.03175847257436829,0.02939035430914813]
for i in range(0,input.shape[0]):
    input[i] = (input[i]-mean[i])/std[i]
input = input.T
print(input)

[[-0.78815137  1.0443219   1.54751675 -0.53346827  0.5828166 ]
 [ 0.73853113  1.5527304   0.90966997 -0.69681712  0.66316031]
 [-1.39882437 -0.4809036  -0.2065619   0.56993839 -0.19934478]
 [-0.48281487  0.0275049   1.06913167 -2.81069838 -1.5500471 ]
 [-0.17747837  1.5527304  -1.80117885  0.69934669 -2.25611277]
 [-1.70416086 -0.4809036  -0.84440868  0.94679814  0.5901782 ]
 [-1.09348787  0.5359134  -1.64171715  0.198799   -0.10321324]
 [ 1.04386763 -0.4809036  -2.12010224  0.198799   -0.10321324]
 [ 0.12785813  0.5359134   1.38805506 -2.70328043 -1.59068152]]


In [3]:
# written by Jingfeng Xia, jxia@wpi.edu

Y,P = TT.predict(input, W, b)
print(raw_input)
print(Y)

[['4' '6' '23' '42.30540715' '-71.06547135']
 ['9' '7' '19' '42.30021944' '-71.06311002']
 ['2' '3' '12' '42.34044966' '-71.08845935']
 ['5' '4' '20' '42.2330858' '-71.12815697']
 ['6' '7' '2' '42.34455947' '-71.14890849']
 ['1' '3' '8' '42.35241815' '-71.06525499']
 ['3' '5' '3' '42.32866284' '-71.08563401']
 ['10' '3' '0' '42.32866284' '-71.08563401']
 ['7' '5' '22' '42.23649723' '-71.12935123']]
[2. 2. 2. 1. 2. 2. 2. 2. 1.]


In [ ]:
!pip install scipy

In [ ]:
import numpy as np
import scipy
from scipy import stats

# a = np.array([0, 2, 2, 1, 0])
# print(stats.zscore(a))

In [ ]:
a = np.mat([[1,3,7],[11,-1,5],[7,2,25],[3,8,-35]]).astype(np.float)
print(a)
a = np.array(a.T)
print(a)
for i in range(0,a.shape[0]):
    a[i] = stats.zscore(a[i])
print(a.T)

In [ ]:
lista = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

lista = [[r[col] for r in lista] for col in range(len(lista[0]))]  
print(lista)

In [ ]:
lista=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]  

lista=[[r[col] for r in lista] for col in range(len(lista[0]))]  
print(lista)

In [ ]:
import preprocess
import LR
import train_test as TT
import sklearn.model_selection as ms
import numpy as np
import math

In [ ]:
# get 5000 rows of cleansed data
# X feature: MONTH,DAY_OF_WEEK,HOUR,DISTRICT(1:12),LATITUDE-36,LONGTITUDE+78
# Y label: DANGER(1,2,3)->low,medium, high
(X,Y)= preprocess.split(20000)

# get training set and test set
train_x, test_x, train_y, test_y = \
    ms.train_test_split(X, Y, test_size=0.2, random_state=5) # training:test = 8:2
# print(train_x.shape, test_x.shape, train_y.shape, test_y.shape)

In [ ]:
# alpha, n_epoch can be tuned
W,b = TT.train(np.mat(train_x), train_y, alpha=0.01, n_epoch=50)
# get W,b for further use
print("W:",W)
print("b:",b)
Y_tr,P_tr = TT.predict(np.mat(train_x), W, b)
Y_te,P_te = TT.predict(np.mat(test_x), W, b)

In [ ]:
train_acc = TT.accuracy(train_y,Y_tr)
print("train accuracy:",train_acc)
test_acc = TT.accuracy(train_y,Y_te)
print("test accuracy:",test_acc)